#! /usr/bin/env python

import rospy
import traceback
from basic_navigation.basic_navigation import BasicNavigation

if __name__ == "__main__":
    rospy.init_node('basic_navigation')
    BN = BasicNavigation()
    CONTROL_RATE = rospy.get_param('~control_rate', 1.0)
    RATE = rospy.Rate(CONTROL_RATE)
    try:
        while not rospy.is_shutdown():
            BN.run_once()
            RATE.sleep()
    except Exception as e:
        rospy.logerr(str(e))
        traceback.print_exc()
    rospy.loginfo('Exiting.')
