#! /usr/bin/env python

import rospy
import traceback
from basic_navigation.topological_navigation import TopologicalNavigation

if __name__ == "__main__":
    rospy.init_node('topological_navigation')
    TN = TopologicalNavigation()
    CONTROL_RATE = rospy.get_param('~control_rate', 2.0)
    RATE = rospy.Rate(CONTROL_RATE)
    rospy.on_shutdown(TN._reset_state)
    try:
        while not rospy.is_shutdown():
            TN.run_once()
            RATE.sleep()
    except Exception as e:
        if type(e) != rospy.exceptions.ROSInterruptException:
            rospy.logerr(str(e))
            traceback.print_exc()
    rospy.loginfo('Exiting.')
