#! /usr/bin/env python

import rospy
import traceback
from basic_navigation.vector_field_navigation import VectorFieldNavigation

if __name__ == "__main__":
    rospy.init_node('vector_field_navigation')
    VFN = VectorFieldNavigation()
    CONTROL_RATE = rospy.get_param('~control_rate', 1.0)
    RATE = rospy.Rate(CONTROL_RATE)
    try:
        while not rospy.is_shutdown():
            VFN.run_once()
            RATE.sleep()
    except Exception as e:
        if type(e) != rospy.exceptions.ROSInterruptException:
            rospy.logerr(str(e))
            traceback.print_exc()
    rospy.loginfo('Exiting.')
