nodes:
- area_name: BRSU_A_E1
  area_type: elevator
  id: 7
  x: 0.0
  y: 0.0
- area_name: BRSU_A_L0_A1
  area_type: area
  id: 9
  x: 0.12
  y: 3.39
- area_name: BRSU_A_L0_A2
  area_type: area
  id: 10
  x: 1.32
  y: 7.46
- area_name: BRSU_A_L0_A3
  area_type: area
  id: 11
  x: 1.47
  y: 13.46
- area_name: BRSU_A_L0_A4
  area_type: junction
  id: 12
  x: 1.88
  y: 21.41
- area_name: BRSU_C_L0_RoomC069
  area_type: room
  id: 14
  x: 51.24
  y: 73.29
- area_name: BRSU_C_L0_C25
  area_type: corridor
  id: 22
  x: 2.94
  y: 73.46
- area_name: BRSU_C_L0_A19
  area_type: area
  id: 23
  x: 6.81
  y: 58.28
- area_name: BRSU_C_L0_A17
  area_type: area
  id: 24
  x: 6.24
  y: 51.07
- area_name: BRSU_C_L0_A15
  area_type: area
  id: 25
  x: 6.52
  y: 43.75
- area_name: BRSU_C_L0_A13
  area_type: area
  id: 26
  x: 2.14
  y: 43.17
- area_name: BRSU_C_L0_A14
  area_type: area
  id: 27
  x: 1.18
  y: 44.99
- area_name: BRSU_C_L0_A16
  area_type: area
  id: 28
  x: 1.15
  y: 51.12
- area_name: BRSU_C_L0_A18
  area_type: area
  id: 29
  x: 1.35
  y: 56.74
- area_name: BRSU_C_L0_A20
  area_type: area
  id: 30
  x: 2.53
  y: 58.96
- area_name: BRSU_C_L0_C26
  area_type: corridor
  id: 31
  x: 2.71
  y: 63.38
- area_name: BRSU_C_L0_C23
  area_type: junction
  id: 33
  x: 5.28
  y: 68.13
- area_name: BRSU_C_L0_C22
  area_type: corridor
  id: 35
  x: 15.29
  y: 67.98
- area_name: BRSU_C_L0_C21
  area_type: corridor
  id: 36
  x: 28.32
  y: 67.64
- area_name: BRSU_C_L0_C20
  area_type: corridor
  id: 37
  x: 37.77
  y: 67.44
- area_name: BRSU_C_L0_C19
  area_type: corridor
  id: 39
  x: 41.39
  y: 67.33
- area_name: BRSU_C_L0_C16
  area_type: corridor
  id: 40
  x: 42.38
  y: 72.54
- area_name: BRSU_C_L0_RoomC022
  area_type: room
  id: 41
  x: 59.43
  y: 25.7
- area_name: BRSU_C_L0_RoomC025
  area_type: room
  id: 42
  x: 59.5
  y: 36.77
- area_name: BRSU_C_L0_C18
  area_type: corridor
  id: 44
  x: 51.36
  y: 67.25
- area_name: BRSU_C_L0_C17
  area_type: corridor
  id: 45
  x: 47.28
  y: 67.13
- area_name: BRSU_C_L0_C15
  area_type: junction
  id: 46
  x: 43.59
  y: 67.3
- area_name: BRSU_C_L0_C14
  area_type: corridor
  id: 47
  x: 44.72
  y: 62.52
- area_name: BRSU_C_L0_C13
  area_type: corridor
  id: 49
  x: 46.68
  y: 54.68
- area_name: BRSU_C_L0_C12
  area_type: corridor
  id: 50
  x: 48.95
  y: 45.16
- area_name: BRSU_C_L0_C11
  area_type: corridor
  id: 51
  x: 51.51
  y: 34.44
- area_name: BRSU_C_L0_C10
  area_type: corridor
  id: 52
  x: 53.41
  y: 27.16
- area_name: BRSU_C_L0_C9
  area_type: corridor
  id: 53
  x: 59.44
  y: 32.2
- area_name: BRSU_C_L0_C7
  area_type: corridor
  id: 55
  x: 45.47
  y: 32.66
- area_name: BRSU_C_L0_C6
  area_type: corridor
  id: 57
  x: 31.61
  y: 32.99
- area_name: BRSU_C_L0_C5
  area_type: corridor
  id: 58
  x: 16.21
  y: 33.41
- area_name: BRSU_C_L0_C3
  area_type: corridor
  id: 60
  x: 2.01
  y: 38.57
- area_name: BRSU_C_L0_C4
  area_type: junction
  id: 61
  x: 4.29
  y: 33.65
- area_name: BRSU_C_L0_C1
  area_type: corridor
  id: 63
  x: 1.89
  y: 28.3
- area_name: BRSU_A_L0_C8
  area_type: corridor
  id: 70
  x: -89.91
  y: 5.3
- area_name: BRSU_A_L0_C7
  area_type: corridor
  id: 71
  x: -79.1
  y: 4.89
- area_name: BRSU_A_L0_C6
  area_type: junction
  id: 72
  x: -67.13
  y: 4.55
- area_name: BRSU_A_L0_C4
  area_type: corridor
  id: 73
  x: -54.12
  y: 4.15
- area_name: BRSU_A_L0_C2
  area_type: corridor
  id: 74
  x: -41.66
  y: 3.85
- area_name: BRSU_A_L0_C1
  area_type: corridor
  id: 75
  x: -26.61
  y: 3.29
- area_name: BRSU_A_L0_A12
  area_type: junction
  id: 76
  x: -12.24
  y: 3.49
- area_name: BRSU_A_L0_A8
  area_type: area
  id: 77
  x: -4.87
  y: 3.61
- area_name: BRSU_C_L0_C8_1
  area_type: junction
  id: 81
  x: 53.81
  y: 32.12
- area_name: BRSU_C_L0_C8_2
  area_type: junction
  id: 82
  x: 51.7
  y: 33.6
- area_name: BRSU_C_L0_C8_3
  area_type: junction
  id: 83
  x: 50.5
  y: 32.6
- area_name: BRSU_C_L0_C8_4
  area_type: junction
  id: 84
  x: 52.7
  y: 30.0
- area_name: BRSU_A_L0_A13
  area_type: area
  id: 95
  x: -11.87
  y: 16.36
- area_name: BRSU_A_L0_A10
  area_type: area
  id: 96
  x: -4.54
  y: 21.06
- area_name: BRSU_A_L0_C10
  area_type: corridor
  id: 98
  x: -104.53
  y: 5.74
- area_name: BRSU_A_L0_C9
  area_type: junction
  id: 99
  x: -98.53
  y: 5.47
- area_name: BRSU_C_L0_C2_1
  area_type: junction
  id: 100
  x: 1.82
  y: 32.42
- area_name: BRSU_C_L0_C2_2
  area_type: junction
  id: 101
  x: 1.8
  y: 35.01
- area_name: BRSU_C_L0_C26_1
  area_type: junction
  id: 102
  x: 2.67
  y: 66.8
- area_name: BRSU_C_L0_C25_1
  area_type: junction
  id: 103
  x: 2.81
  y: 69.44
connections:
- - 53
  - 41
- - 53
  - 42
- - 81
  - 53
- - 84
  - 52
- - 46
  - 40
- - 46
  - 45
- - 45
  - 44
- - 44
  - 14
- - 46
  - 39
- - 39
  - 37
- - 37
  - 36
- - 36
  - 35
- - 35
  - 33
- - 31
  - 30
- - 30
  - 29
- - 29
  - 28
- - 28
  - 27
- - 27
  - 26
- - 26
  - 25
- - 23
  - 30
- - 60
  - 26
- - 61
  - 58
- - 58
  - 57
- - 57
  - 55
- - 55
  - 83
- - 12
  - 63
- - 11
  - 12
- - 10
  - 11
- - 9
  - 10
- - 7
  - 9
- - 77
  - 76
- - 76
  - 75
- - 75
  - 74
- - 74
  - 73
- - 73
  - 72
- - 72
  - 71
- - 71
  - 70
- - 70
  - 99
- - 99
  - 98
- - 12
  - 96
- - 95
  - 76
- - 9
  - 77
- - 82
  - 51
- - 51
  - 50
- - 49
  - 47
- - 47
  - 46
- - 101
  - 60
- - 100
  - 63
- - 102
  - 31
- - 81
  - 84
- - 81
  - 83
- - 81
  - 82
- - 83
  - 82
- - 83
  - 84
- - 82
  - 84
- - 61
  - 100
- - 61
  - 101
- - 100
  - 101
- - 11
  - 76
- - 33
  - 102
- - 103
  - 102
- - 103
  - 33
- - 103
  - 22
