global_frame: /map
robot_base_frame: /ropod/base_link
update_frequency: 1.0
publish_frequency: 1.0
static_map: true
rolling_window: false
resolution: 0.1
transform_tolerance: 0.3
always_send_full_costmap: false

min_obstacle_height: 0.0
footprint: [[-0.33, 0.33], [0.33, 0.33], [0.33, -0.33], [-0.33, -0.33]]

# inflation layer
inflation_radius: 1.0
cost_scaling_factor: 5.0

# obstacle layer
max_obstacle_height: 2.0
obstacle_range: 8.0
raytrace_range: 10.0

observation_sources: laser_scan_sensor
laser_scan_sensor:
    sensor_frame: /rslidar_projected_front
    data_type: LaserScan
    topic: /projected_scan_front
    marking: true
    clearing: true
